package com.techfamz.slimshotai.nativepreview

import kotlin.math.PI
import kotlin.math.cos
import kotlin.math.sin

/**
 * The Kotlin half of the animatable-parameter evaluator — a function-for-function
 * port of `lib/features/video_editor/logic/animation/animatable_double.dart`.
 *
 * A parameter's value is resolved by Flutter in the preview and by this file in
 * the export, so every envelope and the whole keyframe evaluator exist twice and
 * nothing in either type system makes the two agree. `AnimatableDoubleTest` and
 * the fixture generated by `tool/generate_envelope_fixture.dart` are the only
 * things that do: a mistranslated branch is an exported file whose effect moves
 * differently from the canvas, with nothing on screen explaining it.
 *
 * **Keep this structurally parallel to the Dart.** Same helper names, same
 * constants, the `when (name)` below mirroring `resolveEnvelope` in its order. A
 * future curve change has to be applicable to both by reading them side by side;
 * a Kotlin-idiomatic restructuring would make that a translation exercise every
 * time.
 *
 * **Everything is `Double`, never `Float`.** Dart has no `float`, so a `Float`
 * anywhere here would round differently from the preview at exactly the last
 * bits the fixture's `1e-5` is meant to leave room for — and the difference
 * compounds through an ease's cubic. The same rule that made the text animation
 * port use `Long` + `ushr`: the port's numeric types are part of the contract,
 * not an implementation detail.
 *
 * Pure arithmetic, no Android imports, no clock and no state — it runs in a
 * local JVM unit test as well as inside the export loop.
 */

// ---------------------------------------------------------------------------
// Keyframes
// ---------------------------------------------------------------------------

/**
 * How a keyframe's value travels towards the next one.
 *
 * The [wireName] is what crosses the channel, and it is the Dart enum's
 * `.name` — lower case — not this enum's Kotlin constant name. **Renaming one
 * is a migration, not an edit.**
 */
internal enum class KeyframeInterpolation(val wireName: String) {
    /**
     * A straight line, and what a freshly placed keyframe carries — so the
     * easing sheet's "None" cell tells the truth about a diamond nobody has
     * shaped yet.
     */
    LINEAR("linear"),

    /** No travel at all: the value stays put until the next keyframe, then jumps. */
    HOLD("hold"),

    SINE_IN("sineIn"),
    SINE_OUT("sineOut"),
    SINE_IN_OUT("sineInOut"),
    QUAD_IN("quadIn"),
    QUAD_OUT("quadOut"),
    QUAD_IN_OUT("quadInOut"),
    CUBIC_IN("cubicIn"),
    CUBIC_OUT("cubicOut"),
    CUBIC_IN_OUT("cubicInOut"),
    BOUNCE_IN("bounceIn"),
    BOUNCE_OUT("bounceOut"),
    BOUNCE_IN_OUT("bounceInOut"),
}

/**
 * The curve the legacy wire name `ease` resolves to.
 *
 * `ease` was the standard cubic in-out and is no longer a value of the enum;
 * every timeline composed from a draft written before the easing families
 * carries the string, so [keyframeInterpolationByName] maps it here. The
 * migration is exact — the curve is unchanged, only its name.
 */
internal val DEFAULT_KEYFRAME_INTERPOLATION = KeyframeInterpolation.CUBIC_IN_OUT

/**
 * An interpolation name this build does not know degrades to the default rather
 * than throwing — a timeline from a newer build must still render.
 */
internal fun keyframeInterpolationByName(name: String?): KeyframeInterpolation {
    if (name == null) return KeyframeInterpolation.LINEAR
    // The one legacy name. See [DEFAULT_KEYFRAME_INTERPOLATION].
    if (name == "ease") return DEFAULT_KEYFRAME_INTERPOLATION
    for (value in KeyframeInterpolation.entries) {
        if (value.wireName == name) return value
    }
    // **LINEAR, not the default curve.** A name this build cannot read is a
    // shape it has no idea about, and guessing one would move the value along a
    // path nobody chose.
    return KeyframeInterpolation.LINEAR
}

/**
 * The eased fraction for [t] (0..1) on [e].
 *
 * A function-for-function port of `applyKeyframeEasing` in
 * `animatable_double.dart`. **Keep it structurally parallel**: same branch
 * order, same constants, same arithmetic spelled the same way, so a future
 * curve change can be applied to both by reading them side by side.
 *
 * Every curve lands on exactly 0 at `t == 0` and 1 at `t == 1` and stays inside
 * that range throughout — the bounce family included, which is why it bounces
 * *within* the range rather than overshooting the way an elastic ease would.
 */
internal fun applyKeyframeEasing(e: KeyframeInterpolation, t: Double): Double {
    if (t <= 0) return 0.0
    if (t >= 1) return 1.0
    return when (e) {
        // HOLD never actually reaches here — `resolveAt` returns the held value
        // before easing — but the `when` must be exhaustive, and a straight line
        // is the honest answer for a caller asking a hold for its *curve*.
        KeyframeInterpolation.LINEAR, KeyframeInterpolation.HOLD -> t
        KeyframeInterpolation.SINE_IN -> 1 - cos((t * PI) / 2)
        KeyframeInterpolation.SINE_OUT -> sin((t * PI) / 2)
        KeyframeInterpolation.SINE_IN_OUT -> -(cos(PI * t) - 1) / 2
        KeyframeInterpolation.QUAD_IN -> t * t
        KeyframeInterpolation.QUAD_OUT -> 1 - (1 - t) * (1 - t)
        KeyframeInterpolation.QUAD_IN_OUT ->
            if (t < 0.5) {
                2 * t * t
            } else {
                val u = -2 * t + 2
                1 - (u * u) / 2
            }
        KeyframeInterpolation.CUBIC_IN -> t * t * t
        KeyframeInterpolation.CUBIC_OUT -> {
            val u = 1 - t
            1 - u * u * u
        }
        KeyframeInterpolation.CUBIC_IN_OUT ->
            if (t < 0.5) {
                4 * t * t * t
            } else {
                val u = -2 * t + 2
                1 - (u * u * u) / 2
            }
        KeyframeInterpolation.BOUNCE_IN -> 1 - bounceOut(1 - t)
        KeyframeInterpolation.BOUNCE_OUT -> bounceOut(t)
        KeyframeInterpolation.BOUNCE_IN_OUT ->
            if (t < 0.5) {
                (1 - bounceOut(1 - 2 * t)) / 2
            } else {
                (1 + bounceOut(2 * t - 1)) / 2
            }
    }
}

/**
 * The standard four-segment bounce — Penner's, the curve every toolkit ships.
 *
 * **The constants are exact and deliberately unrounded**, matching the Dart
 * digit for digit. A "tidied" 0.98 on either side would be a divergence the
 * fixture catches but nobody could explain.
 *
 * Note `1 / d1` and friends are `Double` division because `d1` is a `Double`;
 * spelling any of these denominators as an integer would be the `1 / 3` trap
 * this file already documents once.
 */
private fun bounceOut(t: Double): Double {
    val n1 = 7.5625
    val d1 = 2.75
    return when {
        t < 1 / d1 -> n1 * t * t
        t < 2 / d1 -> {
            val u = t - 1.5 / d1
            n1 * u * u + 0.75
        }
        t < 2.5 / d1 -> {
            val u = t - 2.25 / d1
            n1 * u * u + 0.9375
        }
        else -> {
            val u = t - 2.625 / d1
            n1 * u * u + 0.984375
        }
    }
}

/** One value pinned at one moment of a clip. */
internal data class Keyframe(
    /** Where in the clip this value sits, **0..1, never seconds**. */
    val progress: Double,
    /** The parameter's value at [progress]. Deliberately unclamped. */
    val value: Double,
    /**
     * How the value travels **from here to the next keyframe**.
     *
     * The interpolation belongs to the segment that *starts* at this keyframe,
     * not the one that ends at it — the convention every editor uses for a
     * hold.
     */
    val interpolation: KeyframeInterpolation = KeyframeInterpolation.LINEAR,
)

// ---------------------------------------------------------------------------
// The parameter
// ---------------------------------------------------------------------------

/**
 * A double that may be constant, shaped by a named envelope, or keyframed.
 *
 * **Resolution order is not negotiable: keyframes, else envelope, else the flat
 * base value.** One keyframe means the user has taken manual control, and the
 * envelope steps aside *entirely* — it does not blend in, scale the result, or
 * contribute at the ends.
 */
internal data class AnimatableDouble(
    /** The value when nothing animates it, and the magnitude an envelope scales. */
    val baseValue: Double,
    /** A name from [ENVELOPE_NAMES], or null for a constant. */
    val envelope: String? = null,
    /**
     * The keyframes. Normally sorted by progress, but [resolveAt] **does not
     * depend on it**: it finds its bracketing pair by comparing progress rather
     * than by trusting position, which removes an entire class of
     * "built through the wrong constructor" bug.
     */
    val keyframes: List<Keyframe> = emptyList(),
) {

    /** Whether anything at all varies this value over the clip. */
    val isAnimated: Boolean
        get() = keyframes.isNotEmpty() || (envelope != null && envelope.isNotEmpty())

    /**
     * The value at [progress] (0..1 through the clip).
     *
     * **Runs per frame in the export**, so it allocates nothing, does no string
     * work beyond the envelope lookup, and walks the keyframes linearly — a
     * keyframe row a user can actually manage holds a handful of points.
     */
    fun resolveAt(progress: Double): Double {
        val p = clamp01(progress)

        // Keyframes first, and exclusively. See the class note.
        val count = keyframes.size
        if (count > 0) {
            // One pass, picking out the two keyframes that bracket `p`: the
            // latest at or before it and the earliest at or after it. Comparing
            // progress rather than walking adjacent pairs is what makes the
            // result independent of the list's order.
            var before: Keyframe? = null
            var after: Keyframe? = null
            for (i in 0 until count) {
                val k = keyframes[i]
                if (k.progress <= p) {
                    // `>=` rather than `>`: with several keyframes on the same
                    // instant the last one written wins, consistently on both
                    // sides of the pair, so the value never depends on which
                    // duplicate the scan met first.
                    if (before == null || k.progress >= before.progress) before = k
                }
                if (k.progress >= p) {
                    if (after == null || k.progress <= after.progress) after = k
                }
            }

            // Before the first keyframe and after the last, the value **holds**
            // — there is no extrapolation. Holding makes one keyframe mean
            // "this value, for the whole clip".
            val b = before ?: return after!!.value
            val a = after ?: return b.value

            // `p` landed exactly on a keyframe, or on a stack of them.
            // Reference identity, mirroring the Dart's `identical`: `Keyframe`
            // is a `data class`, so `==` would also collapse two *distinct*
            // keyframes that happen to carry equal fields — which is a
            // different question from "the scan picked the same object twice".
            if (b === a) return b.value

            // A held keyframe keeps its value right up to the next one. The
            // flag belongs to the segment that *starts* at `before`.
            if (b.interpolation == KeyframeInterpolation.HOLD) return b.value

            val span = a.progress - b.progress
            // Two keyframes can sit on the same instant — a user can drag one
            // onto another, and rejecting that is a UI concern, not this
            // evaluator's. Dividing by the span here would produce NaN and
            // paint a black frame.
            if (span <= 0) return a.value

            val t = (p - b.progress) / span
            val eased = applyKeyframeEasing(b.interpolation, t)
            return b.value + (a.value - b.value) * eased
        }

        val name = envelope
        if (name == null || name.isEmpty()) return baseValue
        return baseValue * resolveEnvelope(name, p)
    }

    companion object {
        /**
         * Reads either shape the Dart `toJson` writes: a **bare number** when
         * nothing is animated, a map otherwise.
         *
         * Defensive throughout, for the same reason the Dart is: a timeline can
         * arrive from a newer build, and a parameter turning into a throw inside
         * the export loop is the worst failure this file could have.
         */
        fun fromWire(value: Any?, fallback: Double = 0.0): AnimatableDouble {
            if (value is Number) return AnimatableDouble(baseValue = value.toDouble())
            if (value !is Map<*, *>) return AnimatableDouble(baseValue = fallback)

            val rawBase = value["baseValue"]
            val baseValue = if (rawBase is Number) rawBase.toDouble() else fallback

            val rawEnvelope = value["envelope"]
            val envelope =
                if (rawEnvelope is String && rawEnvelope.isNotEmpty()) rawEnvelope else null

            val rawKeyframes = value["keyframes"]
            val keyframes = ArrayList<Keyframe>()
            if (rawKeyframes is List<*>) {
                for (entry in rawKeyframes) {
                    // A malformed entry is skipped rather than failing the whole
                    // parameter: losing one keyframe still renders the clip.
                    if (entry is Map<*, *>) keyframes.add(keyframeFromWire(entry))
                }
            }

            // Sorted here as `AnimatableDouble.sorted` does on the Dart side.
            // Correctness of the *value* does not depend on it (see
            // [keyframes]); consistency of anything that reads the list by
            // position does.
            keyframes.sortBy { it.progress }
            return AnimatableDouble(
                baseValue = baseValue,
                envelope = envelope,
                keyframes = keyframes,
            )
        }

        private fun keyframeFromWire(json: Map<*, *>): Keyframe {
            val rawProgress = json["progress"]
            val rawValue = json["value"]
            val rawInterpolation = json["interpolation"]
            return Keyframe(
                // Progress is clip-relative 0..1 by definition, so a value
                // outside it is meaningless rather than merely unusual.
                progress = clamp01(if (rawProgress is Number) rawProgress.toDouble() else 0.0),
                value = if (rawValue is Number) rawValue.toDouble() else 0.0,
                interpolation = keyframeInterpolationByName(rawInterpolation as? String),
            )
        }
    }
}

// ---------------------------------------------------------------------------
// Envelopes
// ---------------------------------------------------------------------------

// Every envelope is a pure function of progress returning a **0..1 multiplier**
// of the base value, so an envelope can only ever take strength away from what
// the user chose with the intensity slider.
//
// **Every envelope lands on exactly 1.0 at p == 1**, so the last frame an
// envelope draws is the clip's own unmodulated intensity and the handover to
// whatever follows is continuous by construction. The full reasoning lives in
// the Dart; it is not repeated here, because two copies of a rationale drift
// exactly as two copies of a constant do.

internal fun clamp01(v: Double): Double {
    // NaN fails every comparison, so it falls through to the explicit check
    // rather than propagating into a keyframe search or a shader uniform. A
    // caller turning seconds into progress divides by a clip duration, and a
    // zero-length clip hands one over.
    if (v.isNaN()) return 0.0
    return if (v < 0) 0.0 else if (v > 1) 1.0 else v
}

/**
 * Slow at both ends, quick through the middle. The default keyframe ease, and
 * the shaping ramps below share it.
 *
 * The standard cubic form, exactly symmetric about 0.5.
 */
internal fun easeInOut(t: Double): Double {
    if (t <= 0) return 0.0
    if (t >= 1) return 1.0
    if (t < 0.5) return 4 * t * t * t
    val u = -2 * t + 2
    return 1 - u * u * u / 2
}

/** **A beat.** The effect drops out and slams back, three times over the clip. */
private fun pulse(p: Double): Double {
    // `cos` of a whole number of cycles starts and ends at 1, which is the
    // endpoint rule for free.
    val wave = cos(2 * PI * PULSE_BEATS * p)
    // Map -1..1 onto 0..1 and bias towards the top so the effect is present
    // more of the time than it is absent.
    val unit = (wave + 1) * 0.5
    return unit * unit
}

/** How many times a `pulse` beats over a clip. */
private const val PULSE_BEATS = 3.0

/** **The effect arrives.** Nothing at the first frame, full strength by the last. */
private fun rampIn(p: Double): Double = easeInOut(p)

/** **The effect clears.** Full strength at the first frame, gone by a third in. */
private fun rampOut(p: Double): Double {
    if (p <= RAMP_OUT_CLEAR_BY) {
        return 1 - easeInOut(p / RAMP_OUT_CLEAR_BY)
    }
    if (p < RAMP_OUT_RETURN_FROM) return 0.0
    val t = (p - RAMP_OUT_RETURN_FROM) / (1 - RAMP_OUT_RETURN_FROM)
    return easeInOut(t)
}

/**
 * `ramp_out` is gone by a third of the clip.
 *
 * Written as `1.0 / 3.0`, matching the Dart's `1 / 3`. Spelling it `1 / 3` here
 * would be **integer division** and give 0, which would make the first arm
 * divide by zero and the second cover the whole clip — the single most likely
 * way this port could have silently diverged, and the reason the fixture samples
 * `p = 0.1` and `p = 0.9` at all.
 */
private const val RAMP_OUT_CLEAR_BY = 1.0 / 3.0

/** …and comes back over the last 15%. */
private const val RAMP_OUT_RETURN_FROM = 0.85

/** **The effect arrives and leaves.** Builds over the first half, releases over the second. */
private fun rampInOut(p: Double): Double {
    if (p <= 0.5) return easeInOut(p / 0.5)
    val t = (p - 0.5) / 0.5
    return 1 - RAMP_IN_OUT_RELEASE_DEPTH * sin(PI * t)
}

/** How far `ramp_in_out` releases at the deepest point of its dip. */
private const val RAMP_IN_OUT_RELEASE_DEPTH = 0.95

/** **A slow breath.** The effect never leaves; it swells and eases twice over the clip. */
private fun throb(p: Double): Double {
    // `sin` of a whole number of cycles is 0 at both ends, so the dip is
    // `(1 - cos)`-shaped: zero depth at p == 0 and p == 1, deepest at each
    // half-cycle.
    val dip = (1 - cos(2 * PI * THROB_BREATHS * p)) * 0.5
    return 1 - THROB_DEPTH * dip
}

/** How far below full strength a breathing envelope dips. */
private const val THROB_DEPTH = 0.45

/** Two breaths over a clip. */
private const val THROB_BREATHS = 2.0

/**
 * Every envelope name, in the order a preset list offers them.
 *
 * Mirrors `kEnvelopeNames`. A name here with no branch in [resolveEnvelope]
 * degrades silently to the base value, so the fixture walks this list rather
 * than a hand-written one.
 */
internal val ENVELOPE_NAMES: List<String> = listOf(
    "pulse",
    "ramp_in",
    "ramp_out",
    "ramp_in_out",
    "throb",
)

/**
 * The multiplier [name] gives at [progress].
 *
 * **An unknown name resolves to 1.0** — the base value, unmodulated — never a
 * throw. A timeline can carry an envelope from a newer build, from a rename that
 * was not migrated, or from a hand-edited draft.
 */
internal fun resolveEnvelope(name: String, progress: Double): Double {
    val p = clamp01(progress)
    return when (name) {
        "pulse" -> pulse(p)
        "ramp_in" -> rampIn(p)
        "ramp_out" -> rampOut(p)
        "ramp_in_out" -> rampInOut(p)
        "throb" -> throb(p)
        else -> 1.0
    }
}
