package com.techfamz.slimshotai.nativepreview

import kotlin.math.PI
import kotlin.math.max
import kotlin.math.sin

/**
 * The Kotlin half of the text animation table — a function-for-function port of
 * `lib/features/video_editor/logic/text_animation_catalog.dart`.
 *
 * Text is drawn by Flutter in the preview and by this file in the export, so
 * every curve exists twice and nothing in either type system makes the two
 * agree. `TextAnimationCurvesTest` and the fixture generated by
 * `tool/generate_animation_fixture.dart` are the only things that do: a changed
 * constant on one side is an exported file that animates differently from the
 * preview, with nothing on screen explaining it.
 *
 * **Keep this structurally parallel to the Dart.** Same helper names, same
 * constants, the `when (id)` below mirroring `kTextAnimations` in its order. A
 * future curve change has to be applicable to both by reading them side by
 * side; a Kotlin-idiomatic restructuring would make that a translation exercise
 * every time.
 *
 * Pure arithmetic, no Android imports — it runs in a local JVM unit test as
 * well as inside the export loop.
 */

/**
 * What one glyph looks like at one instant.
 *
 * The defaults are the **resting state** — the glyph exactly as the static text
 * draws it. An in-animation must return this at `p == 1` and an out-animation at
 * `p == 0`, or the text jumps the frame the animation ends.
 *
 * A `data class` with defaults on purpose: the unknown-id test asserts
 * `TextGlyphState() == state`, which is the renderer's contract that an id from
 * a newer build draws as plain static text rather than throwing inside the
 * export loop.
 */
internal data class TextGlyphState(
    /** 0..1, multiplied into the glyph's own alpha. */
    val opacity: Double = 1.0,
    /**
     * Horizontal displacement in **glyph-height units**, positive right.
     *
     * Not pixels and not a fraction of the text box: a slide must travel the
     * same *visual* distance whether the text is 14pt or 140pt.
     */
    val offsetX: Double = 0.0,
    /** Vertical displacement in glyph-height units, positive **down**. */
    val offsetY: Double = 0.0,
    /** Uniform scale about the glyph's own centre. 1 is resting. */
    val scale: Double = 1.0,
    /** Rotation about the glyph's own centre, in **radians**, clockwise. */
    val rotation: Double = 0.0,
    /** 0..1 sweep for colour-fill effects. 1 — fully filled — is resting. */
    val fillProgress: Double = 1.0,
)

/** Which end of an overlay's life an animation belongs to. */
internal enum class TextAnimationCategory {
    /** Plays once as the text appears. Rests at `p == 1`. */
    IN,

    /** Plays once as the text leaves. Starts from rest at `p == 0`. */
    OUT,

    /** Repeats for the whole span; `p == 0` and `p == 1` must agree. */
    LOOP,
}

/** How long an overlay's in- and out-animations actually run. */
internal data class TextAnimationDurations(
    val inSeconds: Double,
    val outSeconds: Double,
)

internal object TextAnimationCurves {

    // -----------------------------------------------------------------------
    // Shared arithmetic
    // -----------------------------------------------------------------------

    private fun clamp01(v: Double): Double = if (v < 0.0) 0.0 else if (v > 1.0) 1.0 else v

    /**
     * How much of the total window a single glyph's own animation occupies.
     *
     * The other 45% is spread as the stagger, so glyphs overlap heavily: a
     * non-overlapping stagger reads as a slow queue rather than one effect
     * travelling through the word.
     */
    private const val GLYPH_SHARE = 0.55

    /**
     * **The one stagger formula**, used by every per-glyph animation here.
     *
     * Glyph 0 starts at `p == 0` and the last glyph *finishes* exactly at
     * `p == 1`. Both endpoints are exact, which is the point: an in-animation
     * whose last glyph finished at `p == 0.98` would snap on its final frame.
     */
    private fun stagger(p: Double, i: Int, n: Int): Double {
        // A one-glyph text must still animate. Dividing by `n - 1` here would
        // be a divide-by-zero, and skipping the animation would make a
        // single-character caption the one case that silently does nothing.
        if (n <= 1) return clamp01(p)

        val delay = (1.0 - GLYPH_SHARE) * (i.toDouble() / (n - 1).toDouble())
        return clamp01((p - delay) / GLYPH_SHARE)
    }

    /**
     * A deterministic pseudo-random unit value for a glyph index.
     *
     * Jitter for shake and wiggle **must not** come from a `Random`: the
     * preview and the export evaluate the same frame independently, and two
     * draws of the same instant have to agree down to the pixel.
     *
     * **`Long` arithmetic and `ushr`, never `Int` and `>>`.** This is the one
     * place in the port where the obvious transcription is measurably wrong: a
     * literal `Int`/`>>` version diverges from the Dart on **1425 of 1600**
     * sampled (index, salt) pairs. Two independent reasons —
     *
     * 1. The multipliers (`2654435761`, `2246822519`, `3266489917`) all exceed
     *    `Int.MAX_VALUE`; they are not even valid `Int` literals here, and a
     *    32-bit multiply wraps negative where this needs the full unsigned
     *    product.
     * 2. `>>` sign-propagates. Once a value is negative Kotlin's `>>` fills
     *    from the left with ones; this hash needs the zero-fill of `ushr`.
     *
     * Dart's ints are 64-bit and every step masks to 32 bits, so `>>` and
     * `>>>` agree *there* — which is exactly the equivalence a translator
     * copying the operator across would be relying on, and it does not survive
     * the move to a signed 32-bit type. Keep the mask at every step too.
     */
    private fun hashUnit(i: Int, salt: Int): Double {
        var h = (i.toLong() * 2654435761L + salt.toLong() * 40503L) and 0xFFFFFFFFL
        h = (h xor (h ushr 16)) and 0xFFFFFFFFL
        h = (h * 2246822519L) and 0xFFFFFFFFL
        h = (h xor (h ushr 13)) and 0xFFFFFFFFL
        h = (h * 3266489917L) and 0xFFFFFFFFL
        h = (h xor (h ushr 16)) and 0xFFFFFFFFL
        return h / 4294967296.0
    }

    // -- easing, written out -------------------------------------------------
    //
    // Flutter's `Curves` has no Kotlin equivalent, so every curve this table
    // uses is an explicit function on both sides. These are the standard
    // definitions, matching the familiar names.

    private fun easeOutCubic(t: Double): Double {
        val u = 1.0 - t
        return 1.0 - u * u * u
    }

    private fun easeInCubic(t: Double): Double = t * t * t

    /** Overshoots past 1 and settles back — a "pop" without a simulation. */
    private fun easeOutBack(t: Double, overshoot: Double = 1.70158): Double {
        val c3 = overshoot + 1.0
        val u = t - 1.0
        return 1.0 + c3 * u * u * u + overshoot * u * u
    }

    private fun easeInBack(t: Double, overshoot: Double = 1.70158): Double {
        val c3 = overshoot + 1.0
        return c3 * t * t * t - overshoot * t * t
    }

    /** A decaying bounce that lands exactly on 1 — three diminishing hops. */
    private fun easeOutBounce(t: Double): Double {
        val n1 = 7.5625
        val d1 = 2.75
        if (t < 1.0 / d1) return n1 * t * t
        if (t < 2.0 / d1) {
            val u = t - 1.5 / d1
            return n1 * u * u + 0.75
        }
        if (t < 2.5 / d1) {
            val u = t - 2.25 / d1
            return n1 * u * u + 0.9375
        }
        val u = t - 2.625 / d1
        return n1 * u * u + 0.984375
    }

    private fun lerp(a: Double, b: Double, t: Double): Double = a + (b - a) * t

    /**
     * `sin` over a whole number of cycles of `p`.
     *
     * Loops go through this rather than a raw `sin(p * something)` because the
     * seam is only invisible when `p == 0` and `p == 1` land on the *same*
     * point of the wave. Anything that is not a whole cycle jumps every wrap.
     */
    private fun cycles(p: Double, count: Double, phase: Double = 0.0): Double =
        sin(2.0 * PI * (p * count + phase))

    // -----------------------------------------------------------------------
    // Durations
    // -----------------------------------------------------------------------

    /**
     * The stock duration for a flat, non-staggered animation.
     *
     * 0.5s is what the old text layer actually played (flutter_animate's
     * default), so legacy animations keep their current feel.
     */
    private const val FLAT_DURATION = 0.5

    private fun flat(@Suppress("UNUSED_PARAMETER") glyphCount: Int): Double = FLAT_DURATION

    /**
     * A staggered animation's duration: a base, plus a beat per character.
     *
     * The floor keeps a one- or two-character text from flashing past too fast
     * to read as an animation; the ceiling keeps a long caption's typing from
     * eating a clip whole.
     */
    private fun staggered(
        glyphCount: Int,
        base: Double = 0.35,
        perGlyph: Double = 0.05,
    ): Double {
        val raw = base + perGlyph * max(0, glyphCount - 1).toDouble()
        return raw.coerceIn(0.4, 2.5)
    }

    /** Bounce and spin need longer to read: compressed, they twitch. */
    private fun staggeredSlow(glyphCount: Int): Double =
        staggered(glyphCount, base = 0.6, perGlyph = 0.05)

    // A loop's natural duration is the length of **one cycle**, not of the
    // overlay: the caller wraps `p` by it for as long as the text is on screen.
    private fun loopCycle(@Suppress("UNUSED_PARAMETER") glyphCount: Int): Double = 1.2

    private fun loopCycleSlow(@Suppress("UNUSED_PARAMETER") glyphCount: Int): Double = 2.4

    // -----------------------------------------------------------------------
    // Curve bodies
    // -----------------------------------------------------------------------

    /**
     * Typing reveals a glyph **whole**, not faded in.
     *
     * The reveal is a step, not a ramp: a fade would smear several characters
     * at partial opacity at once, which reads as a blur rather than as typing.
     */
    private fun typing(p: Double, i: Int, n: Int): TextGlyphState {
        val g = stagger(p, i, n)
        return TextGlyphState(opacity = if (g > 0.0) 1.0 else 0.0)
    }

    /** Untyping is typing run backwards: the last character goes first. */
    private fun untyping(p: Double, i: Int, n: Int): TextGlyphState {
        // Reverse the index so the stagger walks right-to-left, which is how a
        // caption deletes itself.
        val g = stagger(p, n - 1 - i, n)
        return TextGlyphState(opacity = if (g >= 1.0) 0.0 else 1.0)
    }

    private fun fadeIn(p: Double): TextGlyphState = TextGlyphState(opacity = clamp01(p))

    private fun fadeOut(p: Double): TextGlyphState = TextGlyphState(opacity = clamp01(1.0 - p))

    // The legacy slide and zoom curves below **move or scale only — they never
    // touch opacity**, and that omission is deliberate. The old layer's arms
    // (`text_overlay_layer.dart`, `_animated`) were bare `scaleXY`/`slideX`/
    // `slideY` calls with no `fadeIn()`/`fadeOut()` alongside them. Adding a
    // fade here would change how projects users have already saved look — the
    // same regression class as resolving a legacy id to the wrong slot.

    /** Grows from nothing — the legacy `zoom_in` / `scale`, begin 0. */
    private fun zoomIn(p: Double): TextGlyphState =
        TextGlyphState(scale = lerp(0.0, 1.0, easeOutCubic(clamp01(p))))

    /** Shrinks *into* place from oversize — the legacy `zoom_out`, begin 2.0. */
    private fun zoomOut(p: Double): TextGlyphState =
        TextGlyphState(scale = lerp(2.0, 1.0, easeOutCubic(clamp01(p))))

    /** Shrinks away to nothing — the legacy `zoom_in_out`, `scaleXY(end: 0)`. */
    private fun zoomInOut(p: Double): TextGlyphState =
        TextGlyphState(scale = lerp(1.0, 0.0, easeInCubic(clamp01(p))))

    /** Swells to double size — the legacy `zoom_out_out`, `scaleXY(end: 2)`. */
    private fun zoomOutOut(p: Double): TextGlyphState =
        TextGlyphState(scale = lerp(1.0, 2.0, easeInCubic(clamp01(p))))

    /**
     * How far a slide travels, in glyph heights.
     *
     * A little over one line: far enough to read as entering from off-frame,
     * short enough that the text is not absent for most of the window.
     */
    private const val SLIDE_DISTANCE = 1.5

    /**
     * Slides are built from one body so the four directions cannot drift apart.
     *
     * `dx`/`dy` point from the animation's *start* towards rest, matching the
     * legacy layer: `slide_up` began below and travelled up.
     */
    private fun slideIn(p: Double, dx: Double, dy: Double): TextGlyphState {
        val t = easeOutCubic(clamp01(p))
        val remaining = 1.0 - t
        return TextGlyphState(
            offsetX = dx * SLIDE_DISTANCE * remaining,
            offsetY = dy * SLIDE_DISTANCE * remaining,
        )
    }

    private fun slideOut(p: Double, dx: Double, dy: Double): TextGlyphState {
        val t = easeInCubic(clamp01(p))
        return TextGlyphState(
            offsetX = dx * SLIDE_DISTANCE * t,
            offsetY = dy * SLIDE_DISTANCE * t,
        )
    }

    /** Overshoots past its resting place and settles — one glyph at a time. */
    private fun bounceIn(p: Double, i: Int, n: Int): TextGlyphState {
        val g = stagger(p, i, n)
        val t = easeOutBounce(g)
        return TextGlyphState(
            // Drops in from above and bounces on the baseline.
            opacity = clamp01(g * 3.0),
            offsetY = -SLIDE_DISTANCE * (1.0 - t),
        )
    }

    private fun bounceOut(p: Double, i: Int, n: Int): TextGlyphState {
        val g = stagger(p, i, n)
        val t = easeInCubic(g)
        return TextGlyphState(
            opacity = clamp01((1.0 - g) * 3.0),
            offsetY = SLIDE_DISTANCE * t,
        )
    }

    /** A small scale overshoot — the "pop" that lands a caption with weight. */
    private fun popIn(p: Double, i: Int, n: Int): TextGlyphState {
        val g = stagger(p, i, n)
        return TextGlyphState(
            opacity = clamp01(g * 3.0),
            scale = lerp(0.4, 1.0, easeOutBack(g)),
        )
    }

    private fun popOut(p: Double, i: Int, n: Int): TextGlyphState {
        val g = stagger(p, i, n)
        return TextGlyphState(
            opacity = clamp01((1.0 - g) * 3.0),
            // `easeInBack` dips slightly *below* zero early, which would flip
            // the glyph inside out; clamping keeps the anticipation without it.
            scale = max(0.0, lerp(1.0, 0.4, easeInBack(g))),
        )
    }

    /** A single hump travelling along the text as it appears. */
    private fun waveIn(p: Double, i: Int, n: Int): TextGlyphState {
        val g = stagger(p, i, n)
        // Half a sine over the glyph's own window: up and back down, ending flat.
        val lift = sin(PI * g)
        return TextGlyphState(
            opacity = clamp01(g * 2.0),
            offsetY = -0.5 * lift,
            // The travel settles, so the resting state is exact at g == 1.
            scale = lerp(0.8, 1.0, easeOutCubic(g)),
        )
    }

    /**
     * The text is already there; the fill colour sweeps through it.
     *
     * Opacity stays at 1 throughout — this is a colour sweep over visible text,
     * not a reveal, and fading it would make it read as a slow fade.
     */
    private fun colourFill(p: Double, i: Int, n: Int): TextGlyphState =
        TextGlyphState(fillProgress = stagger(p, i, n))

    /** Rises from below with a slight lean, glyph by glyph. */
    private fun riseIn(p: Double, i: Int, n: Int): TextGlyphState {
        val g = stagger(p, i, n)
        val t = easeOutCubic(g)
        return TextGlyphState(
            opacity = clamp01(g * 2.0),
            offsetY = SLIDE_DISTANCE * (1.0 - t),
        )
    }

    /** Spins into place — rotation and scale resolving together. */
    private fun spinIn(p: Double, i: Int, n: Int): TextGlyphState {
        val g = stagger(p, i, n)
        val t = easeOutCubic(g)
        return TextGlyphState(
            opacity = clamp01(g * 2.0),
            // A half-turn is enough to read as a spin; a full turn at typical
            // durations is too fast to follow and reads as a flicker.
            scale = lerp(0.3, 1.0, t),
            rotation = -PI * (1.0 - t),
        )
    }

    /** Sinks away downward, fading — the counterpart to [riseIn]. */
    private fun sinkOut(p: Double, i: Int, n: Int): TextGlyphState {
        val g = stagger(p, i, n)
        val t = easeInCubic(g)
        return TextGlyphState(
            opacity = clamp01((1.0 - g) * 2.0),
            offsetY = SLIDE_DISTANCE * t,
        )
    }

    // -- loops ---------------------------------------------------------------
    //
    // Every loop below is a whole number of cycles in `p`, so `p == 0` and
    // `p == 1` are the same instant of the motion and the wrap is invisible.
    // Per-glyph phase is a *fraction of the cycle*, which keeps that true
    // however many glyphs there are.

    /** A wave travelling along the text, forever. */
    private fun waveLoop(p: Double, i: Int, n: Int): TextGlyphState {
        // One full wavelength spread across the text, so the crest visibly
        // travels from the first character to the last rather than every glyph
        // bobbing together.
        val phase = if (n <= 1) 0.0 else i.toDouble() / n.toDouble()
        return TextGlyphState(offsetY = -0.35 * cycles(p, 1.0, phase))
    }

    /** A gentle breath — the whole block scaling as one. */
    private fun pulseLoop(p: Double): TextGlyphState =
        TextGlyphState(scale = 1.0 + 0.08 * cycles(p, 1.0))

    /** A nervous shake: each glyph jitters on its own axis, deterministically. */
    private fun shakeLoop(p: Double, i: Int): TextGlyphState {
        // The hash sets each glyph's *phase*, not its amplitude, so neighbours
        // are out of step — which is what makes it read as shake rather than as
        // the block vibrating — while staying seamless at the wrap.
        val px = hashUnit(i, 1)
        val py = hashUnit(i, 2)
        // Several cycles per loop — a shake is fast by nature — and both counts
        // are whole, so the seam holds.
        return TextGlyphState(
            offsetX = 0.08 * cycles(p, 6.0, px),
            offsetY = 0.08 * cycles(p, 5.0, py),
        )
    }

    /** A slow, loose wobble: shake's lazy cousin, with rotation. */
    private fun wiggleLoop(p: Double, i: Int): TextGlyphState {
        val pr = hashUnit(i, 3)
        val po = hashUnit(i, 4)
        return TextGlyphState(
            offsetY = 0.05 * cycles(p, 2.0, po),
            rotation = 0.09 * cycles(p, 2.0, pr),
        )
    }

    /** The fill sweeps through the text repeatedly. */
    private fun colourCycleLoop(p: Double, i: Int, n: Int): TextGlyphState {
        val phase = if (n <= 1) 0.0 else i.toDouble() / n.toDouble()
        val v = (p + phase) % 1.0
        // Triangle, not sawtooth: a sawtooth's reset is a hard jump in colour
        // on every glyph, once per loop.
        return TextGlyphState(fillProgress = if (v < 0.5) v * 2.0 else (1.0 - v) * 2.0)
    }

    // -----------------------------------------------------------------------
    // The table
    // -----------------------------------------------------------------------
    //
    // Mirrors `kTextAnimations` in the Dart, in the same order (in, out, loop),
    // so the two can be diffed by eye. The category and duration tables below
    // key off the same ids.

    /**
     * The curve for [id] at progress [p], for glyph [i] of [n].
     *
     * **Never throws.** An id can arrive from a draft written by a newer build
     * or from a rename that has not been migrated; the renderer's contract is
     * that an unknown animation draws as plain static text, exactly as `none`
     * does. A throw here would happen inside the export loop, where it would
     * read as an export failure rather than as a stale draft.
     */
    fun stateAt(id: String?, p: Double, i: Int, n: Int): TextGlyphState = when (id) {
        // -- in --
        "typing" -> typing(p, i, n)
        "fade_in" -> fadeIn(p)
        "zoom_in" -> zoomIn(p)
        "zoom_out" -> zoomOut(p)
        "slide_up" -> slideIn(p, 0.0, 1.0)
        "slide_down" -> slideIn(p, 0.0, -1.0)
        "slide_left" -> slideIn(p, 1.0, 0.0)
        "slide_right" -> slideIn(p, -1.0, 0.0)
        "bounce_in" -> bounceIn(p, i, n)
        "pop_in" -> popIn(p, i, n)
        "wave_in" -> waveIn(p, i, n)
        "colour_fill" -> colourFill(p, i, n)
        "rise_in" -> riseIn(p, i, n)
        "spin_in" -> spinIn(p, i, n)

        // -- out --
        "untyping" -> untyping(p, i, n)
        "fade_out" -> fadeOut(p)
        "zoom_in_out" -> zoomInOut(p)
        "zoom_out_out" -> zoomOutOut(p)
        "slide_up_out" -> slideOut(p, 0.0, -1.0)
        "slide_down_out" -> slideOut(p, 0.0, 1.0)
        "slide_left_out" -> slideOut(p, -1.0, 0.0)
        "slide_right_out" -> slideOut(p, 1.0, 0.0)
        "bounce_out" -> bounceOut(p, i, n)
        "pop_out" -> popOut(p, i, n)
        "sink_out" -> sinkOut(p, i, n)

        // -- loop --
        "wave_loop" -> waveLoop(p, i, n)
        "pulse_loop" -> pulseLoop(p)
        "shake_loop" -> shakeLoop(p, i)
        "colour_cycle_loop" -> colourCycleLoop(p, i, n)
        "wiggle_loop" -> wiggleLoop(p, i)

        else -> TextGlyphState()
    }

    /**
     * How long [id] wants to run for a text of [glyphCount] characters.
     *
     * Part of the contract as much as the curves are: the Kotlin side decides
     * how long a window runs, so a divergence here shifts every glyph's `p`
     * even with identical curve bodies.
     *
     * An unknown id answers 0 — it has no window because [stateAt] will rest
     * through it anyway.
     */
    fun naturalDuration(id: String, glyphCount: Int): Double = when (id) {
        // -- in --
        "typing" -> staggered(glyphCount)
        "fade_in", "zoom_in", "zoom_out",
        "slide_up", "slide_down", "slide_left", "slide_right",
        -> flat(glyphCount)
        "bounce_in" -> staggeredSlow(glyphCount)
        "pop_in", "wave_in", "colour_fill", "rise_in" -> staggered(glyphCount)
        "spin_in" -> staggeredSlow(glyphCount)

        // -- out --
        "untyping" -> staggered(glyphCount)
        "fade_out", "zoom_in_out", "zoom_out_out",
        "slide_up_out", "slide_down_out", "slide_left_out", "slide_right_out",
        -> flat(glyphCount)
        "bounce_out", "pop_out", "sink_out" -> staggered(glyphCount)

        // -- loop --
        "wave_loop", "pulse_loop", "shake_loop", "wiggle_loop" -> loopCycle(glyphCount)
        "colour_cycle_loop" -> loopCycleSlow(glyphCount)

        else -> 0.0
    }

    /** Which slot each catalog id belongs to; an unknown id belongs to none. */
    private fun categoryOf(id: String): TextAnimationCategory? = when (id) {
        "typing", "fade_in", "zoom_in", "zoom_out",
        "slide_up", "slide_down", "slide_left", "slide_right",
        "bounce_in", "pop_in", "wave_in", "colour_fill", "rise_in", "spin_in",
        -> TextAnimationCategory.IN

        "untyping", "fade_out", "zoom_in_out", "zoom_out_out",
        "slide_up_out", "slide_down_out", "slide_left_out", "slide_right_out",
        "bounce_out", "pop_out", "sink_out",
        -> TextAnimationCategory.OUT

        "wave_loop", "pulse_loop", "shake_loop", "colour_cycle_loop", "wiggle_loop",
        -> TextAnimationCategory.LOOP

        else -> null
    }

    // -----------------------------------------------------------------------
    // Lookup
    // -----------------------------------------------------------------------

    /**
     * Legacy ids that meant **different animations in different slots**.
     *
     * The old widget layer switched on one string per slot, and two ids
     * appeared in both switches meaning opposite things: `'fade'` was
     * `fadeIn()` in the in-slot and `fadeOut()` in the out-slot; `'scale'` was
     * `scaleXY(begin: 0)` in the in-slot and `scaleXY(end: 0)` in the out-slot
     * — which is character for character what `zoom_in_out` does.
     *
     * So the slot, not the id alone, decides. Resolving `'fade'` from the
     * out-slot to `fade_in` would play a saved project's exit **backwards**:
     * the text would fade *in* as it left.
     */
    private val legacyInIds = mapOf(
        "fade" to "fade_in",
        "scale" to "zoom_in",
    )

    private val legacyOutIds = mapOf(
        "fade" to "fade_out",
        "scale" to "zoom_in_out",
    )

    /**
     * The animation a persisted [id] means **in the slot it was read from**.
     *
     * It resolves the legacy tables above, then **refuses an animation
     * belonging to a different slot** — and that second rule is doing real
     * work, not being defensive for its own sake.
     *
     * The old layer's out-slot switch handled *only* the `_out`-suffixed
     * names. A bare `'slide_up'`, `'zoom_in'` or `'zoom_out'` sitting in
     * `outAnimation` fell through its default arm and played **no
     * out-animation at all** — and those bare names are real catalog ids, so a
     * plain id lookup would find the in-variant and cheerfully animate. That
     * would *add* an exit animation to a project that never had one, which is
     * as much a regression as losing one.
     *
     * It looks like an oversight that `'slide_up'` in the out-slot does
     * nothing. It is not: it is bug-for-bug fidelity to the drafts people
     * already have.
     */
    fun resolveAnimationId(id: String, slot: TextAnimationCategory): String? {
        if (id.isEmpty() || id == "none") return null

        val legacy = when (slot) {
            TextAnimationCategory.IN -> legacyInIds
            TextAnimationCategory.OUT -> legacyOutIds
            // Loops were never persisted by the old layer, so there is nothing
            // to translate; a loop id is already a catalog id.
            TextAnimationCategory.LOOP -> emptyMap()
        }

        val resolved = legacy[id] ?: id
        return if (categoryOf(resolved) == slot) resolved else null
    }

    /**
     * How long the in- and out-animations of one text overlay actually run.
     *
     * The ids are resolved **in their own slots** first, so a legacy `'fade'`
     * in the out-slot is timed as `fade_out` and a bare `'slide_up'` there
     * contributes nothing at all — the same rule [resolveAnimationId]
     * enforces, applied before any arithmetic.
     *
     * [speed] scales both inversely — a 2x speed halves them — so the
     * animation tab's speed control means what a user expects.
     *
     * When the two together do not fit inside [spanSeconds] they are
     * **compressed proportionally**, never dropped. Dropping one would make
     * the exported file differ from the preview with nothing on screen to
     * explain it, which is the same class of fault as an export silently
     * losing a transition.
     */
    fun resolveDurations(
        spanSeconds: Double,
        inAnimationId: String?,
        outAnimationId: String?,
        glyphCount: Int,
        speed: Double,
    ): TextAnimationDurations {
        // A zero or negative speed would divide to infinity; a caller reading a
        // half-initialised model can hand one over, so guard rather than trust.
        val rate = if (speed > 0.0) speed else 1.0

        val inId = inAnimationId?.let { resolveAnimationId(it, TextAnimationCategory.IN) }
        val outId = outAnimationId?.let { resolveAnimationId(it, TextAnimationCategory.OUT) }

        var inSeconds = if (inId == null) 0.0 else naturalDuration(inId, glyphCount) / rate
        var outSeconds = if (outId == null) 0.0 else naturalDuration(outId, glyphCount) / rate

        // A span can legitimately be zero — an overlay mid-creation, or one
        // trimmed to nothing — and a negative one means the model is
        // inconsistent. Neither may produce a negative duration downstream.
        val span = if (spanSeconds > 0.0) spanSeconds else 0.0

        val total = inSeconds + outSeconds
        if (total > span && total > 0.0) {
            val squeeze = span / total
            inSeconds *= squeeze
            outSeconds *= squeeze
        }

        return TextAnimationDurations(inSeconds = inSeconds, outSeconds = outSeconds)
    }
}
