package com.techfamz.slimshotai.nativepreview

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import kotlin.math.abs

/**
 * Holds the Kotlin evaluator to the same sampled values `AnimatableDouble` in
 * Dart produces.
 *
 * A parameter is resolved by Flutter in the preview and by this Kotlin in the
 * export, so every envelope and the whole keyframe evaluator exist twice.
 * Nothing in either type system makes the two agree; this fixture is the only
 * thing that does. When it fails, the exported file's effect moves differently
 * from the canvas.
 *
 * The fixture is generated by `dart run tool/generate_envelope_fixture.dart`.
 * A deliberate change to `animatable_double.dart` means regenerating it and
 * re-running **this** test — the Dart-side pin passes by construction, because
 * it is generated from the code it checks, so only this side can actually fail
 * for a real reason.
 *
 * **Be honest about what a green run here proves.** The fixture catches
 * *divergence tomorrow* — this port drifting from the Dart, or the Dart drifting
 * from this port. It cannot tell you the envelopes are shaped right today: both
 * sides would agree just as happily on a curve that is wrong. That question is
 * answered by `animatable_double_test.dart`, which asserts the curves'
 * *properties* (the endpoint rule, monotonicity, the 0..1 bound) against what
 * they are meant to be rather than against what they currently are.
 */
class AnimatableDoubleTest {

    /**
     * `1e-5` rather than exact equality. The fixture is rounded to six decimal
     * places and the two languages' `sin`/`cos` may differ in the last bits;
     * `1e-5` is far tighter than any visible difference at canvas resolution
     * while leaving room for that.
     *
     * **Do not loosen this to make a failure pass.** A real divergence is a
     * ported constant or a mistranslated operator — `1 / 3` written as integer
     * division, an ease's cubic done in `Float` — and it is orders of magnitude
     * larger than this.
     */
    private val tolerance = 1e-5

    private fun fixture(): JsonValue.JsonObject {
        val stream = javaClass.getResourceAsStream("/animatable_fixture.json")
            ?: error(
                "animatable_fixture.json missing from test resources. " +
                    "Run: dart run tool/generate_envelope_fixture.dart"
            )
        return FixtureJson.parse(stream.bufferedReader().use { it.readText() })
    }

    /**
     * Every assertion names the case it came from.
     *
     * A bare "expected 0.5 got 0.7" inside a table of hundreds of rows is
     * unusable, and this test exists to be read when it fails: the envelope
     * name — or the keyframe configuration's name — together with `p` is what
     * tells you which curve, and which branch of it, drifted.
     */
    private fun assertClose(where: String, expected: Double, actual: Double) {
        if (abs(expected - actual) > tolerance) {
            throw AssertionError(
                "$where: expected $expected but was $actual " +
                    "(difference ${abs(expected - actual)}, tolerance $tolerance)"
            )
        }
    }

    /**
     * Progress travels as a number, except NaN, which JSON cannot spell — the
     * generator writes the string `"nan"` for it. Dropping that row instead
     * would leave the one arm of `clamp01` that exists for a real crash (a
     * caller dividing seconds by a zero-length clip) untested on this side.
     */
    private fun JsonValue.JsonObject.progress(key: String): Double =
        when (val v = fields[key]) {
            is JsonValue.JsonNumber -> v.value
            is JsonValue.JsonString -> {
                require(v.value == "nan") { "'$key' holds unknown marker '${v.value}'" }
                Double.NaN
            }
            else -> error("'$key' is neither a number nor a marker")
        }

    /** How a sampled progress reads in a failure message. */
    private fun show(p: Double): String = if (p.isNaN()) "nan" else p.toString()

    @Test
    fun `envelope samples match the shared fixture`() {
        val rows = fixture().array("envelopes")
        assertTrue("fixture has no envelope samples", rows.isNotEmpty())

        for (row in rows) {
            val name = row.string("envelope")
            val p = row.double("p")
            assertClose(
                "envelope '$name' at p=$p",
                row.double("value"),
                resolveEnvelope(name, p),
            )
        }
    }

    /**
     * The degrade rule that keeps a timeline from a newer build renderable: an
     * envelope name this build has never heard of resolves to 1.0 — the base
     * value, unmodulated — rather than throwing inside the export loop.
     */
    @Test
    fun `unknown envelope names rest at the base value`() {
        val rows = fixture().array("unknownEnvelopes")
        assertTrue("fixture has no unknown-envelope samples", rows.isNotEmpty())

        for (row in rows) {
            val name = row.string("envelope")
            val p = row.double("p")
            val actual = resolveEnvelope(name, p)
            assertClose("unknown envelope '$name' at p=$p", row.double("value"), actual)
            // Belt and braces: the fixture says 1.0 today, and this says it must
            // keep saying 1.0 whatever it was regenerated from.
            assertEquals("unknown envelope '$name' at p=$p", 1.0, actual, 0.0)
        }
    }

    /**
     * Progress outside 0..1, and NaN.
     *
     * Kotlin and Dart both make every comparison against NaN false, so the
     * `isNaN` guard has to come first on both sides — spelled any other way the
     * clamp would let a NaN through into a shader uniform and paint a black
     * frame.
     */
    @Test
    fun `out of range progress is clamped the same way`() {
        val rows = fixture().array("clampedEnvelopes")
        assertTrue("fixture has no clamp samples", rows.isNotEmpty())

        for (row in rows) {
            val name = row.string("envelope")
            val p = row.progress("p")
            assertClose(
                "envelope '$name' at clamped p=${show(p)}",
                row.double("value"),
                resolveEnvelope(name, p),
            )
        }
    }

    /**
     * The keyframe evaluator, case by case.
     *
     * Each case's parameter is **rebuilt from the fixture's own record of it**
     * rather than being hand-written here a second time. Hand-writing the table
     * on this side would mean the test could pass while the two sides evaluated
     * different parameters — the exact class of silent disagreement the fixture
     * exists to catch.
     */
    @Test
    fun `keyframe cases match the shared fixture`() {
        val cases = fixture().array("keyframeCases")
        assertTrue("fixture has no keyframe cases", cases.isNotEmpty())

        for (case in cases) {
            val name = case.string("name")
            val parameter = AnimatableDouble(
                baseValue = case.double("baseValue"),
                envelope = case.stringOrNull("envelope"),
                // Deliberately **not** sorted: the fixture records the order the
                // Dart parameter actually holds, and `resolveAt` brackets by
                // comparing progress rather than by trusting position. A port
                // that sorted here would hide a broken scan.
                keyframes = case.array("keyframes").map {
                    Keyframe(
                        progress = it.double("progress"),
                        value = it.double("value"),
                        interpolation = keyframeInterpolationByName(it.string("interpolation")),
                    )
                },
            )

            assertEquals(
                "isAnimated for case '$name'",
                case.bool("isAnimated"),
                parameter.isAnimated,
            )

            for (sample in case.array("samples")) {
                val p = sample.progress("p")
                assertClose(
                    "keyframe case '$name' at p=${show(p)}",
                    sample.double("value"),
                    parameter.resolveAt(p),
                )
            }
        }
    }

    /**
     * The order-independence rule, asserted directly rather than only through
     * the fixture's two same-shaped cases agreeing by coincidence.
     *
     * The `const` Dart constructor cannot sort, so a parameter genuinely reaches
     * the evaluator unsorted. Bracketing by comparing progress is what makes
     * that safe on both sides.
     */
    @Test
    fun `keyframe order does not change the result`() {
        val sorted = listOf(
            Keyframe(0.0, 0.0, KeyframeInterpolation.LINEAR),
            Keyframe(0.5, 1.0, KeyframeInterpolation.HOLD),
            Keyframe(1.0, 0.25),
        )
        val scrambled = listOf(sorted[2], sorted[0], sorted[1])
        val a = AnimatableDouble(baseValue = 0.0, keyframes = sorted)
        val b = AnimatableDouble(baseValue = 0.0, keyframes = scrambled)
        for (p in listOf(0.0, 0.1, 0.25, 0.5, 0.75, 0.9, 1.0)) {
            assertEquals("order-independence at p=$p", a.resolveAt(p), b.resolveAt(p), 0.0)
        }
    }

    /**
     * `1 / 3` is integer division in Kotlin and would give 0 — the single most
     * likely way this port could have silently diverged, since it makes
     * `ramp_out`'s first arm divide by zero and its second cover the whole clip.
     *
     * Pinned here as well as through the fixture because the fixture's failure
     * would read as "ramp_out drifted" and this one reads as what it is.
     */
    @Test
    fun `ramp_out clears by exactly a third`() {
        // A zero clear-by point makes the first arm divide by zero, and
        // `easeInOut` swallows the resulting NaN through its `<= 0` guard — so
        // this checks the *start*, where 1 - easeInOut(0/0) is NaN and nothing
        // downstream hides it. Verified by reintroducing `(1 / 3)` and watching
        // this fail alongside the fixture sweep.
        val atStart = resolveEnvelope("ramp_out", 0.0)
        assertTrue("ramp_out at p=0 returned $atStart, not a number", !atStart.isNaN())
        assertClose("ramp_out at its start", 1.0, atStart)
        assertClose("ramp_out at its clear-by point", 0.0, resolveEnvelope("ramp_out", 1.0 / 3.0))
        assertClose("ramp_out at its end", 1.0, resolveEnvelope("ramp_out", 1.0))
        // Halfway down the first arm. With an integer-divided clear-by this is
        // 0 rather than the eased value, which the fixture also catches at
        // p=0.1 — pinned here too so the failure reads as what it is.
        assertClose(
            "ramp_out halfway through its clear",
            1 - easeInOut(0.5),
            resolveEnvelope("ramp_out", 1.0 / 6.0),
        )
        assertTrue(
            "ramp_out must be cleared through the clip's middle",
            resolveEnvelope("ramp_out", 0.6) == 0.0,
        )
    }

    /**
     * The endpoint rule every envelope is written to satisfy: full strength on
     * the clip's last frame, so the handover to whatever follows is continuous
     * and nothing pops on the cut.
     *
     * Asserted against the *rule* rather than against the fixture, so it would
     * catch a curve that was regenerated into being wrong on both sides.
     */
    @Test
    fun `every envelope rests at full strength on the last frame`() {
        for (name in ENVELOPE_NAMES) {
            assertClose("envelope '$name' at p=1", 1.0, resolveEnvelope(name, 1.0))
        }
    }

    /**
     * And the 0..1 bound: an envelope shapes an intensity, it never exceeds it.
     * A multiplier above 1 would push a parameter past the maximum its own UI
     * offers.
     */
    @Test
    fun `no envelope ever exceeds the base value`() {
        for (name in ENVELOPE_NAMES) {
            var p = 0.0
            while (p <= 1.0) {
                val v = resolveEnvelope(name, p)
                assertTrue("envelope '$name' at p=$p returned $v, above 1", v <= 1.0 + tolerance)
                assertTrue("envelope '$name' at p=$p returned $v, below 0", v >= -tolerance)
                p += 0.001
            }
        }
    }

    /**
     * The wire reader, which is how a parameter actually reaches this file from
     * the composer. The unanimated case is a **bare number** in every draft
     * already saved, so it has to load as a plain value.
     */
    @Test
    fun `fromWire reads both shapes and never throws`() {
        assertEquals("a bare number", 0.6, AnimatableDouble.fromWire(0.6).baseValue, 0.0)
        assertEquals("a bare int", 2.0, AnimatableDouble.fromWire(2).baseValue, 0.0)
        assertEquals(
            "an absent field falls back",
            0.35,
            AnimatableDouble.fromWire(null, fallback = 0.35).baseValue,
            0.0,
        )
        assertEquals(
            "an unreadable field falls back",
            0.35,
            AnimatableDouble.fromWire("nonsense", fallback = 0.35).baseValue,
            0.0,
        )

        val full = AnimatableDouble.fromWire(
            mapOf(
                "baseValue" to 0.8,
                "envelope" to "pulse",
                "keyframes" to listOf(
                    mapOf("progress" to 1.0, "value" to 0.9, "interpolation" to "hold"),
                    mapOf("progress" to 0.0, "value" to 0.1, "interpolation" to "linear"),
                    // Malformed entries are skipped, not fatal: losing one
                    // keyframe still renders the clip.
                    "not a map",
                    mapOf("progress" to "quoted", "value" to null),
                ),
            ),
        )
        assertEquals("baseValue", 0.8, full.baseValue, 0.0)
        assertEquals("envelope", "pulse", full.envelope)
        assertEquals("keyframe count", 3, full.keyframes.size)
        // The degenerate entry defaults to (0, 0, ease) and sorts to the front
        // alongside the real 0.0 keyframe.
        assertEquals("sorted by progress", 0.0, full.keyframes.first().progress, 0.0)
        assertEquals("sorted by progress", 1.0, full.keyframes.last().progress, 0.0)
        assertEquals(
            "an unknown interpolation name degrades to ease",
            KeyframeInterpolation.EASE,
            keyframeInterpolationByName("not_a_real_interpolation"),
        )
    }
}
