package com.techfamz.slimshotai.nativepreview

/**
 * A tiny JSON reader for the shared animation fixture.
 *
 * There are two off-the-shelf options and both are worse here.
 * `android.util.JSONObject` is stubbed in local unit tests to throw
 * "not mocked", so it cannot parse anything; the real `org.json:json` artifact
 * works but is an extra download, and this is the only thing in the module's
 * unit tests that would need it. The fixture is generated by
 * `tool/generate_animation_fixture.dart` with a flat, known shape — objects of
 * strings, numbers, nulls, and arrays of those — so a few dozen lines cover it
 * and the test suite runs with JUnit alone and no network.
 *
 * Deliberately not general: no escapes beyond the ones `JsonEncoder` actually
 * emits, no nested arrays. It parses **this** file. If the fixture ever grows a
 * shape this does not handle, it fails loudly at parse time rather than
 * returning something plausible and wrong.
 */
internal sealed interface JsonValue {
    data class JsonString(val value: String) : JsonValue
    data class JsonNumber(val value: Double) : JsonValue
    data class JsonBool(val value: Boolean) : JsonValue
    data object JsonNull : JsonValue
    data class JsonArray(val items: List<JsonValue>) : JsonValue
    data class JsonObject(val fields: Map<String, JsonValue>) : JsonValue
}

internal class FixtureJson(private val source: String) {
    private var pos = 0

    companion object {
        fun parse(source: String): JsonValue.JsonObject {
            val parser = FixtureJson(source)
            parser.skipWhitespace()
            val value = parser.parseValue()
            parser.skipWhitespace()
            require(parser.pos >= parser.source.length) {
                "trailing content at offset ${parser.pos}"
            }
            return value as? JsonValue.JsonObject
                ?: error("fixture root is not an object")
        }
    }

    private fun skipWhitespace() {
        while (pos < source.length && source[pos].isWhitespace()) pos++
    }

    private fun expect(c: Char) {
        require(pos < source.length && source[pos] == c) {
            "expected '$c' at offset $pos but found " +
                (if (pos < source.length) "'${source[pos]}'" else "end of input")
        }
        pos++
    }

    private fun parseValue(): JsonValue {
        skipWhitespace()
        require(pos < source.length) { "unexpected end of input" }
        return when (val c = source[pos]) {
            '{' -> parseObject()
            '[' -> parseArray()
            '"' -> JsonValue.JsonString(parseString())
            't', 'f' -> parseBool()
            'n' -> parseNull()
            else -> {
                require(c == '-' || c.isDigit()) { "unexpected '$c' at offset $pos" }
                parseNumber()
            }
        }
    }

    private fun parseObject(): JsonValue.JsonObject {
        expect('{')
        val fields = LinkedHashMap<String, JsonValue>()
        skipWhitespace()
        if (pos < source.length && source[pos] == '}') {
            pos++
            return JsonValue.JsonObject(fields)
        }
        while (true) {
            skipWhitespace()
            val key = parseString()
            skipWhitespace()
            expect(':')
            fields[key] = parseValue()
            skipWhitespace()
            when (source[pos]) {
                ',' -> pos++
                '}' -> { pos++; return JsonValue.JsonObject(fields) }
                else -> error("expected ',' or '}' at offset $pos")
            }
        }
    }

    private fun parseArray(): JsonValue.JsonArray {
        expect('[')
        val items = ArrayList<JsonValue>()
        skipWhitespace()
        if (pos < source.length && source[pos] == ']') {
            pos++
            return JsonValue.JsonArray(items)
        }
        while (true) {
            items.add(parseValue())
            skipWhitespace()
            when (source[pos]) {
                ',' -> pos++
                ']' -> { pos++; return JsonValue.JsonArray(items) }
                else -> error("expected ',' or ']' at offset $pos")
            }
        }
    }

    private fun parseString(): String {
        expect('"')
        val sb = StringBuilder()
        while (true) {
            require(pos < source.length) { "unterminated string" }
            when (val c = source[pos]) {
                '"' -> { pos++; return sb.toString() }
                '\\' -> {
                    pos++
                    when (val esc = source[pos]) {
                        '"', '\\', '/' -> sb.append(esc)
                        'b' -> sb.append('\b')
                        'f' -> sb.append('')
                        'n' -> sb.append('\n')
                        'r' -> sb.append('\r')
                        't' -> sb.append('\t')
                        'u' -> {
                            val hex = source.substring(pos + 1, pos + 5)
                            sb.append(hex.toInt(16).toChar())
                            pos += 4
                        }
                        else -> error("bad escape '\\$esc' at offset $pos")
                    }
                    pos++
                }
                else -> { sb.append(c); pos++ }
            }
        }
    }

    private fun parseNumber(): JsonValue.JsonNumber {
        val start = pos
        if (source[pos] == '-') pos++
        while (pos < source.length && (source[pos].isDigit() || source[pos] in ".eE+-")) {
            pos++
        }
        val text = source.substring(start, pos)
        return JsonValue.JsonNumber(
            text.toDoubleOrNull() ?: error("bad number '$text' at offset $start"),
        )
    }

    private fun parseBool(): JsonValue.JsonBool {
        return when {
            source.startsWith("true", pos) -> { pos += 4; JsonValue.JsonBool(true) }
            source.startsWith("false", pos) -> { pos += 5; JsonValue.JsonBool(false) }
            else -> error("bad literal at offset $pos")
        }
    }

    private fun parseNull(): JsonValue {
        require(source.startsWith("null", pos)) { "bad literal at offset $pos" }
        pos += 4
        return JsonValue.JsonNull
    }
}

// -- accessors, so the test reads like it would with a real JSON library -----

internal fun JsonValue.JsonObject.array(key: String): List<JsonValue.JsonObject> {
    val value = fields[key] ?: error("fixture has no '$key' array")
    val array = value as? JsonValue.JsonArray ?: error("'$key' is not an array")
    return array.items.map { it as? JsonValue.JsonObject ?: error("'$key' holds a non-object") }
}

internal fun JsonValue.JsonObject.double(key: String): Double =
    (fields[key] as? JsonValue.JsonNumber)?.value ?: error("'$key' is not a number")

internal fun JsonValue.JsonObject.int(key: String): Int = double(key).toInt()

internal fun JsonValue.JsonObject.string(key: String): String =
    (fields[key] as? JsonValue.JsonString)?.value ?: error("'$key' is not a string")

internal fun JsonValue.JsonObject.bool(key: String): Boolean =
    (fields[key] as? JsonValue.JsonBool)?.value ?: error("'$key' is not a boolean")

/** A field that is legitimately `null` in the fixture, such as an unresolved id. */
internal fun JsonValue.JsonObject.stringOrNull(key: String): String? =
    when (val v = fields[key]) {
        null, JsonValue.JsonNull -> null
        is JsonValue.JsonString -> v.value
        else -> error("'$key' is neither a string nor null")
    }
