package com.techfamz.slimshotai.nativepreview

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import kotlin.math.abs

/**
 * Holds the Kotlin curve port to the same sampled values the Dart catalog
 * produces.
 *
 * Text is rendered by Flutter in the preview and by this Kotlin in the export,
 * so every curve in `text_animation_catalog.dart` exists twice. Nothing in
 * either type system makes the two agree; this fixture is the only thing that
 * does. When it fails, the exported file animates differently from the preview.
 *
 * The fixture is generated by `dart run tool/generate_animation_fixture.dart`.
 * A deliberate curve change means regenerating it and re-running **this** test
 * — the Dart-side pin passes by construction, because it is generated from the
 * code it checks, so only this side can actually catch a divergence.
 */
class TextAnimationCurvesTest {

    /**
     * `1e-5` rather than exact equality. The fixture is rounded to six decimal
     * places and the two languages' `sin`/`pow` may differ in the last bits;
     * `1e-5` is far tighter than any visible difference at canvas resolution
     * while leaving room for that.
     *
     * **Do not loosen this to make a failure pass.** A real divergence is a
     * ported constant or a mistranslated operator — `_hashUnit` done in `Int`
     * with `>>` rather than `Long` with `ushr`, say — and it is orders of
     * magnitude larger than this.
     */
    private val tolerance = 1e-5

    private fun fixture(): JsonValue.JsonObject {
        val stream = javaClass.getResourceAsStream("/text_animation_fixture.json")
            ?: error(
                "text_animation_fixture.json missing from test resources. " +
                    "Run: dart run tool/generate_animation_fixture.dart"
            )
        return FixtureJson.parse(stream.bufferedReader().use { it.readText() })
    }

    /**
     * Every assertion names the sample it came from.
     *
     * A bare "expected 0.5 got 0.7" inside a table of sixteen hundred rows is
     * unusable, and this test exists to be read when it fails: the id, `p`,
     * `i` and `n` are what tell you which curve, and which branch of it,
     * drifted.
     */
    private fun assertChannel(
        where: String,
        channel: String,
        expected: Double,
        actual: Double,
    ) {
        // **NaN must fail, and a tolerance check alone lets it through.** Every
        // comparison against NaN is false, so `abs(NaN - x) > tolerance` is
        // false and a port that had started producing NaN — an integer
        // division, a divide by zero, a `sqrt` of a negative — would pass this
        // fixture silently while rendering nothing on a device. Found in the
        // sibling `AnimatableDoubleTest` by deliberately injecting the bug.
        if (!actual.isFinite() || abs(expected - actual) > tolerance) {
            throw AssertionError(
                "$where $channel: expected $expected but was $actual " +
                    "(difference ${abs(expected - actual)}, tolerance $tolerance)"
            )
        }
    }

    @Test
    fun `curve samples match the shared fixture`() {
        val samples = fixture().array("samples")
        assertTrue("fixture has no curve samples", samples.isNotEmpty())

        for (row in samples) {
            val id = row.string("id")
            val p = row.double("p")
            val i = row.int("i")
            val n = row.int("n")
            val where = "$id p=$p i=$i n=$n"

            val state = TextAnimationCurves.stateAt(id, p, i, n)
            assertChannel(where, "opacity", row.double("opacity"), state.opacity)
            assertChannel(where, "offsetX", row.double("offsetX"), state.offsetX)
            assertChannel(where, "offsetY", row.double("offsetY"), state.offsetY)
            assertChannel(where, "scale", row.double("scale"), state.scale)
            assertChannel(where, "rotation", row.double("rotation"), state.rotation)
            assertChannel(
                where,
                "fillProgress",
                row.double("fillProgress"),
                state.fillProgress,
            )
        }
    }

    @Test
    fun `natural durations match the shared fixture`() {
        val durations = fixture().array("durations")
        assertTrue("fixture has no duration samples", durations.isNotEmpty())

        for (row in durations) {
            val id = row.string("id")
            val glyphCount = row.int("glyphCount")
            assertChannel(
                "$id glyphCount=$glyphCount",
                "naturalDuration",
                row.double("seconds"),
                TextAnimationCurves.naturalDuration(id, glyphCount),
            )
        }
    }

    /**
     * Legacy ids resolve by **slot**, not by id alone: `'fade'` meant fade-in
     * in the in-slot and fade-out in the out-slot, and a bare in-only id
     * (`slide_up`, `zoom_in`, `zoom_out`) sitting in the out-slot played
     * nothing at all. Getting the first wrong plays a saved project's exit
     * backwards; getting the second wrong adds an exit animation to a project
     * that never had one. Both change how drafts people already have look.
     */
    @Test
    fun `slot resolution matches the shared fixture`() {
        val resolution = fixture().array("resolution")
        assertTrue("fixture has no resolution samples", resolution.isNotEmpty())

        for (row in resolution) {
            val id = row.string("id")
            val slotName = row.string("slot")
            val slot = when (slotName) {
                "in" -> TextAnimationCategory.IN
                "out" -> TextAnimationCategory.OUT
                "loop" -> TextAnimationCategory.LOOP
                else -> error("unknown slot $slotName")
            }
            assertEquals(
                "resolveAnimationId('$id', $slotName)",
                row.stringOrNull("resolved"),
                TextAnimationCurves.resolveAnimationId(id, slot),
            )
        }
    }

    @Test
    fun `resolved durations match the shared fixture`() {
        val rows = fixture().array("durationResolution")
        assertTrue("fixture has no durationResolution samples", rows.isNotEmpty())

        for (row in rows) {
            val inId = row.stringOrNull("inId")
            val outId = row.stringOrNull("outId")
            val span = row.double("spanSeconds")
            val speed = row.double("speed")
            val glyphCount = row.int("glyphCount")
            val where = "span=$span speed=$speed glyphCount=$glyphCount " +
                "in=$inId out=$outId"

            val resolved = TextAnimationCurves.resolveDurations(
                spanSeconds = span,
                inAnimationId = inId,
                outAnimationId = outId,
                glyphCount = glyphCount,
                speed = speed,
            )
            assertChannel(where, "inSeconds", row.double("inSeconds"), resolved.inSeconds)
            assertChannel(where, "outSeconds", row.double("outSeconds"), resolved.outSeconds)
        }
    }

    /**
     * The contract the renderer relies on: an id it has never heard of — a
     * draft written by a newer build, or a renamed animation — draws the text
     * exactly as static text, rather than throwing inside the export loop.
     */
    @Test
    fun `an unknown or absent id rests instead of throwing`() {
        for (id in listOf(null, "", "none", "not_a_real_id", "circleOpen")) {
            val state = TextAnimationCurves.stateAt(id, 0.5, 2, 5)
            assertEquals("opacity for id=$id", 1.0, state.opacity, 0.0)
            assertEquals("offsetX for id=$id", 0.0, state.offsetX, 0.0)
            assertEquals("offsetY for id=$id", 0.0, state.offsetY, 0.0)
            assertEquals("scale for id=$id", 1.0, state.scale, 0.0)
            assertEquals("rotation for id=$id", 0.0, state.rotation, 0.0)
            assertEquals("fillProgress for id=$id", 1.0, state.fillProgress, 0.0)
            assertEquals("resting state for id=$id", TextGlyphState(), state)
        }
    }
}
